// @vitest-environment jsdom
import { act, fireEvent, render, renderHook, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { webcrypto } from "node:crypto";
import type { CapabilityUiNavigationHandler, ViewRef } from "@deepfield/capability-sdk";
import { IndustryResearchCapability } from "../ui/IndustryResearchCapability.js";
import { CompanyResearchPanel } from "../ui/CompanyResearchPanel.js";
import { researchRun, researchSummary } from "../ui/company-research-test-fixtures.js";
import { makeFakeApi } from "../../../apps/desktop/src/renderer/renderer-test-helpers.js";
import type { CapabilityItem, ItemCompanyView } from "../contracts/index.js";
import type { PreparedResearch } from "./drafts.js";
import { revision } from "./drafts.js";
import { useCompanyResearch } from "../ui/use-company-research.js";
import { configuredSettings } from "../../../apps/desktop/src/renderer/features/settings/settings-test-fixtures.js";
afterEach(() => vi.unstubAllGlobals());

it("opens the new-topic parent page and refreshes the real topic after creation", async () => {
  const api = makeFakeApi();
  const created = { id: "new-topic", type: "industry-research", industry: "机器人", researchScope: "仓储", notes: "首批", createdAt: "2026-09-23", updatedAt: "2026-09-23" } as CapabilityItem;
  api.industryResearch.listItems.mockResolvedValueOnce([]).mockResolvedValue([created]);
  api.industryResearch.getItem.mockResolvedValue(created);
  api.industryResearch.listCompanies.mockResolvedValue([]);
  let handler!: CapabilityUiNavigationHandler;
  render(<IndustryResearchCapability api={api} onClose={() => {}} navigation={{ register(value) { handler = value; return () => {}; } }} />);
  await waitFor(() => expect(handler).toBeDefined());
  const preview: ViewRef = { capabilityId: "company-research", viewId: "topics", input: {} };
  const open = (view: ViewRef) => handler.open(view, { view, signal: new AbortController().signal, commit(change) { if (!handler.canLeave()) return false; change(); return true; } });
  await act(async () => { expect(await open(preview)).toEqual({ status: "opened" }); });
  expect(screen.getByRole("heading", { name: "研究主题" })).toBeTruthy();
  expect(api.industryResearch.createItem).not.toHaveBeenCalled();
  expect(handler.canLeave()).toBe(true);
  const actual: ViewRef = { capabilityId: "company-research", viewId: "companies", input: { itemId: created.id } };
  await act(async () => { expect(await open(actual)).toEqual({ status: "opened" }); });
  expect(screen.getByRole("heading", { name: "机器人" })).toBeTruthy();
  act(() => fireEvent.click(screen.getByRole("button", { name: "‹ 返回调研列表" })));
  expect(screen.getByRole("button", { name: "机器人仓储" })).toBeTruthy();
});

it("refreshes the visible company report after a same-company completed navigation", async () => {
  const api = makeFakeApi();
  const run = researchRun({ rawReportText: "即将删除的报告正文" });
  const item = { id: run.itemId, type: "industry-research", industry: "芯片", createdAt: "2026-09-01", updatedAt: "2026-09-01" } as CapabilityItem;
  const company = { id: run.companyId, itemId: run.itemId, name: "甲", normalizedName: "甲", profileStatus: "ready", createdAt: "2026-09-01", updatedAt: "2026-09-01" } as ItemCompanyView;
  api.industryResearch.listItems.mockResolvedValue([item]);
  api.industryResearch.getItem.mockResolvedValue(item);
  api.industryResearch.listCompanies.mockResolvedValue([company]);
  api.companyResearch.getState.mockResolvedValue({ runs: [researchSummary(run)], globalActiveRun: null });
  api.companyResearch.getRun.mockResolvedValue(run);
  let handler!: CapabilityUiNavigationHandler;
  render(<IndustryResearchCapability api={api} onClose={() => {}} navigation={{ register(value) { handler = value; return () => {}; } }} />);
  await waitFor(() => expect(handler).toBeDefined());
  const view: ViewRef = { capabilityId: "company-research", viewId: "company", input: { itemId: item.id, companyId: company.id } };
  const open = () => handler.open(view, { view, signal: new AbortController().signal, commit(change) { if (!handler.canLeave()) return false; change(); return true; } });
  await act(async () => { expect(await open()).toEqual({ status: "opened" }); });
  expect(await screen.findByText("即将删除的报告正文")).toBeTruthy();
  api.companyResearch.getState.mockResolvedValue({ runs: [], globalActiveRun: null });
  api.companyResearch.getRun.mockResolvedValue(undefined);
  await act(async () => { expect(await open()).toEqual({ status: "opened" }); });
  await waitFor(() => expect(screen.queryByText("即将删除的报告正文")).toBeNull());
  expect(screen.getByRole("button", { name: "开始调研" })).toBeTruthy();
});

it("keeps the exact requested report selected through its initial async refresh", async () => {
  const api = makeFakeApi();
  const requested = researchRun({ id: "old" as any, rawReportText: "指定历史版本内容" });
  const latest = researchRun({ id: "latest" as any, rawReportText: "最新报告内容" });
  api.companyResearch.getState.mockResolvedValue({ runs: [researchSummary(latest), researchSummary(requested)], globalActiveRun: null });
  api.companyResearch.getRun.mockImplementation(async (_item, _company, id) => id === "old" ? requested : latest);
  render(<CompanyResearchPanel api={api} itemId={requested.itemId} companyId={requested.companyId} topicName="主题" companyName="甲" requestedRunId="old" />);
  expect(await screen.findByText("指定历史版本内容")).toBeTruthy();
  expect(screen.queryByText("最新报告内容")).toBeNull();
});
it.each(["changed", "deleted"] as const)("keeps the current page when a report is %s during navigation preparation", async state => {
  vi.stubGlobal("crypto", webcrypto);
  const api = makeFakeApi();
  const run = researchRun();
  const item = { id: run.itemId, type: "industry-research", industry: "芯片", createdAt: "2026-09-01", updatedAt: "2026-09-01" } as CapabilityItem;
  const company = { id: run.companyId, itemId: run.itemId, name: "甲", normalizedName: "甲", profileStatus: "ready", createdAt: "2026-09-01", updatedAt: "2026-09-01" } as ItemCompanyView;
  api.industryResearch.listItems.mockResolvedValue([item]); api.industryResearch.getItem.mockResolvedValue(item);
  let finishPreparation!: (value: ItemCompanyView[]) => void;
  api.industryResearch.listCompanies.mockReturnValue(new Promise(resolve => { finishPreparation = resolve; }));
  api.companyResearch.getRun.mockResolvedValue(run);
  let handler!: CapabilityUiNavigationHandler;
  render(<IndustryResearchCapability api={api} onClose={() => {}} navigation={{ register(value) { handler = value; return () => {}; } }} />);
  await screen.findByRole("heading", { name: "研究主题" });
  const view: ViewRef = { capabilityId: "company-research", viewId: "report", input: { itemId: run.itemId, companyId: run.companyId, runId: run.id, revision: revision(run) } };
  const commit = vi.fn((change: () => void) => { change(); return true; });
  const opening = handler.open(view, { view, signal: new AbortController().signal, commit });
  await waitFor(() => expect(api.industryResearch.listCompanies).toHaveBeenCalled());
  api.companyResearch.getRun.mockResolvedValue(state === "deleted" ? undefined : { ...run, rawReportText: "changed after main resolution" });
  await act(async () => {
    finishPreparation([company]);
    expect(await opening).toMatchObject({ status: state === "deleted" ? "not_found" : "blocked" });
  });
  expect(commit).not.toHaveBeenCalled();
  expect(screen.getByRole("heading", { name: "研究主题" })).toBeTruthy();
  expect(screen.queryByRole("heading", { name: "甲" })).toBeNull();
});
it.each(["retry", "retryStructuring"] as const)("allows a new report revision after an explicit successful %s from a reference", async method => {
  vi.stubGlobal("crypto", webcrypto);
  const api = makeFakeApi(); api.settings.get.mockResolvedValue(configuredSettings());
  const initial = researchRun({ status: method === "retry" ? "research_failed" : "structure_failed", lastFailureCode: method === "retry" ? "model_failed" : "structuring_failed" });
  const updated = researchRun({ rawReportText: "用户重试后的新报告" });
  api.companyResearch.retryFailed.mockResolvedValue(updated);
  api.companyResearch.retryStructuring.mockResolvedValue(updated);
  api.companyResearch.getState.mockResolvedValue({ runs: [researchSummary(initial)], globalActiveRun: null });
  api.companyResearch.getRun.mockResolvedValue(initial);
  const { result } = renderHook(() => useCompanyResearch(api, initial.itemId, initial.companyId, initial.id, revision(initial)));
  await waitFor(() => expect(result.current.selectedRun).toEqual(initial));
  api.companyResearch.getState.mockResolvedValue({ runs: [researchSummary(updated)], globalActiveRun: null });
  api.companyResearch.getRun.mockResolvedValue(updated);
  await act(async () => { if (method === "retry") await result.current.retry({ direction: initial.direction, asOfDate: initial.asOfDate }); else await result.current.retryStructuring(); });
  await waitFor(() => expect(result.current.selectedRun).toEqual(updated));
  expect(result.current.error).toBeUndefined();
});
it("continues rejecting unsolicited report changes after a failed explicit retry", async () => {
  vi.stubGlobal("crypto", webcrypto);
  const api = makeFakeApi(); api.settings.get.mockResolvedValue(configuredSettings());
  const initial = researchRun({ status: "structure_failed", lastFailureCode: "structuring_failed" });
  api.companyResearch.getState.mockResolvedValue({ runs: [researchSummary(initial)], globalActiveRun: null });
  api.companyResearch.getRun.mockResolvedValue(initial);
  const { result } = renderHook(() => useCompanyResearch(api, initial.itemId, initial.companyId, initial.id, revision(initial)));
  await waitFor(() => expect(result.current.selectedRun).toEqual(initial));
  api.companyResearch.retryStructuring.mockRejectedValueOnce(new Error("offline failure"));
  await act(async () => { await expect(result.current.retryStructuring()).rejects.toThrow("offline failure"); });
  api.companyResearch.getRun.mockResolvedValue({ ...initial, rawReportText: "unrequested change" });
  act(() => api.companyResearch.subscribe.mock.calls[0]![0]({ type: "state_changed", itemId: initial.itemId, companyId: initial.companyId, runId: initial.id }));
  await waitFor(() => expect(result.current.error?.message).toMatch(/报告内容已更新/));
  expect(result.current.selectedRun).toBeUndefined();
});
it("retargets a deleted report pin so later refresh keeps the replacement selected", async () => {
  const api = makeFakeApi();
  const deleted = researchRun({ id: "deleted" as any });
  const next = researchRun({ id: "next" as any, rawReportText: "保留报告" });
  api.companyResearch.getState.mockResolvedValue({ runs: [researchSummary(deleted), researchSummary(next)], globalActiveRun: null });
  api.companyResearch.getRun.mockImplementation(async (_item, _company, id) => id === deleted.id ? deleted : next);
  const { result } = renderHook(() => useCompanyResearch(api, deleted.itemId, deleted.companyId, deleted.id));
  await waitFor(() => expect(result.current.selectedRun?.id).toBe(deleted.id));
  api.companyResearch.getState.mockResolvedValue({ runs: [researchSummary(next)], globalActiveRun: null });
  api.companyResearch.getRun.mockImplementation(async (_item, _company, id) => id === next.id ? next : undefined);
  await act(async () => { await result.current.deleteSelected(); });
  expect(result.current.selectedRunId).toBe(next.id);
  act(() => api.companyResearch.subscribe.mock.calls[0]![0]({ type: "state_changed", itemId: next.itemId, companyId: next.companyId, runId: next.id }));
  await waitFor(() => { expect(result.current.selectedRun?.id).toBe(next.id); expect(result.current.selectedRunId).toBe(next.id); });
});
it("opens an editable draft with one submit button, invalidates on editing and preserves input on conflict", async () => {
  const api = makeFakeApi();
  const item = { id: "topic", type: "industry-research", industry: "芯片", createdAt: "2026-09-01", updatedAt: "2026-09-01" } as CapabilityItem;
  const company = { id: "company", itemId: "topic", name: "甲", normalizedName: "甲", profileStatus: "ready", createdAt: "2026-09-01", updatedAt: "2026-09-01" } as ItemCompanyView;
  api.industryResearch.listItems.mockResolvedValue([item]); api.industryResearch.getItem.mockResolvedValue(item); api.industryResearch.listCompanies.mockResolvedValue([company]);
  const prepared: PreparedResearch = { draftRef: { capabilityId: "company-research", draftId: "draft", revision: "1" }, parameters: { itemId: "topic", companyId: "company", direction: "product_and_technology", asOfDate: "2026-09-01", focusScope: "原始范围" } };
  let invalidations = 0;
  api.researchDraft = { get: async () => ({ ok: true, prepared }), invalidate: async () => { invalidations++; return { ok: true, prepared: { ...prepared, draftRef: { ...prepared.draftRef, revision: "2" } } }; }, update: async () => ({ ok: false, code: "revision_changed" }), submit: async () => ({ ok: true }) };
  let handler!: CapabilityUiNavigationHandler;
  render(<IndustryResearchCapability api={api} onClose={() => {}} navigation={{ register(value) { handler = value; return () => {}; } }} />);
  await waitFor(() => expect(handler).toBeDefined());
  const view: ViewRef = { capabilityId: "company-research", viewId: "research-draft", input: { draftId: "draft", revision: "1" } };
  await act(async () => { expect(await handler.open(view, { view, signal: new AbortController().signal, commit(change) { if (!handler.canLeave()) return false; change(); return true; } })).toEqual({ status: "opened" }); });
  const scope = await screen.findByRole("textbox", { name: "关注范围（可选）" });
  fireEvent.change(scope, { target: { value: "人工输入必须保留" } });
  fireEvent.change(scope, { target: { value: "人工输入必须保留两次" } });
  await waitFor(() => expect(invalidations).toBe(1));
  expect(handler.canLeave()).toBe(false);
  fireEvent.submit(scope.closest("form")!);
  expect(await screen.findByText(/草稿版本已变更或不可用/)).toBeTruthy();
  expect((scope as HTMLTextAreaElement).value).toBe("人工输入必须保留两次");
  expect(screen.queryByText(/确认提交/)).toBeNull();
});
